### ISSUE TITLE
ConnectionResetError: Cannot write to closing transport

### ISSUE THREAD

**Issue by meremortals70** [sebr/bhyve-home-assistant#156]
**Describe the bug**
System Error in HA Logs after installing 2022.9 beta

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/bhyve/pybhyve/websocket.py:57 
Integration: Orbit B-hyve (documentation) 
First occurred: 7:33:36 PM (1 occurrences) 
Last logged: 7:33:36 PM

Error doing job: Task exception was never retrieved
```
Traceback (most recent call last):
  File "/config/custom_components/bhyve/pybhyve/websocket.py", line 57, in _ping
    await self._ws.send_str(json.dumps({"event": "ping"}))
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_ws.py", line 151, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 690, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 601, in _send_frame
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```

Please let me know if you need more. Can’t download the diagnostics on my iPad.

**Comment by sebr** [comment]
@meremortals70 sorry that I didn't follow up on this... lost track. Did this get resolved in a later version? I have never seen this issue.

**Comment by SeeThisIsMe** [comment]
I have had exactly the same issue for almost a year. Before that it worked fine. Still ongoing now with the latest version of HA and bhyve HACS integration.

 I have 4 of the hose timer devices and always get this error with at least one of them every day. What happens is when the scheduled irrigation time comes around it start and then stops immediately with this error. If I then open the bhyve app it shows the watering working fine.

**Comment by sebr** [comment]
Are all the hose timers configured to start irrigating at the same time?

**Comment by SeeThisIsMe** [comment]
Nope. The water pressure is a bit low for more than one at a time. So the schedules are in a sequence with 5-6 minutes between when one finishes and the next one starts.

**Comment by dinan5** [comment]
I have the same exact issue. Thank you.

**Comment by dinan5** [comment]
Are there any updates on this issue? Thank you.

**Comment by AnthonyBe** [comment]
Oddly, I haven't see the error for a while (I'm now on HA 2024.6.4)

**Comment by dinan5** [comment]
I'm still having the issue. I have three HA instances that all connect to 2 Orbit controllers.  I'm wondering if its too much traffic.  I'm experimenting by disabling some of the instances.
