### ISSUE TITLE
Websocket error on restart

### ISSUE THREAD

**Issue by disforw** [sebr/bhyve-home-assistant#177]
**Describe the bug**
I am receiving the following error every time HA starts.

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/bhyve/pybhyve/websocket.py:57 
Integration: Orbit B-hyve (documentation) 
First occurred: 7:57:02 AM (1 occurrences) 
Last logged: 7:57:02 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/bhyve/pybhyve/websocket.py", line 57, in _ping
    await self._ws.send_str(json.dumps({"event": "ping"}))
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_ws.py", line 151, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 690, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/http_websocket.py", line 601, in _send_frame
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport

**Comment by sebr** [comment]
Sorry mate, I haven't been able to track this down and unfortunately the bhyve api is a bit flakey. In the future I might consider a back-off and retry mechanism to make this more resilient, but not for now.
