### ISSUE TITLE
KeyError: 'sprinkler_type' after upgrade to 0.1.0

### ISSUE THREAD

**Issue by NotSteveAtGithub** [sebr/bhyve-home-assistant#2]
upgraded from 0.0.1 to 0.1.0, now getting this error in the logs:

2020-01-15 06:40:34 ERROR (MainThread) [homeassistant.components.switch] Error while setting up platform bhyve
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/bhyve/switch.py", line 31, in async_setup_platform
    BHyveSwitch(bhyve, device, zone, name, sensor_type["icon"],)
  File "/config/custom_components/bhyve/switch.py", line 46, in __init__
    super().__init__(bhyve, device, name, icon, DEVICE_CLASS_SWITCH)
  File "/config/custom_components/bhyve/__init__.py", line 151, in __init__
    self._setup(device)
  File "/config/custom_components/bhyve/switch.py", line 74, in _setup
    "sprinkler_type": zone["sprinkler_type"],
KeyError: 'sprinkler_type'

**Comment by sebr** [comment]
Thanks for the report - fixed in 0.1.1
