### ISSUE TITLE
Does not create switch, Error messages in logs 0.1.1

### ISSUE THREAD

**Issue by retroneo** [sebr/bhyve-home-assistant#3]
error from callback <bound method Listener.on_message of <Listener(Thread-4, initial daemon)>>: on_message() missing 1 required positional argument: 'message'

and

error from callback <bound method Listener.on_open of <Listener(Thread-4, initial daemon)>>: on_open() missing 1 required positional argument: 'ws'

**Comment by monsieurlatte** [comment]
I was able to add the switch, you have to wait until you add the new setup first then add the switch.  However I get this when I try to toggle switch.  

object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 133, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 205, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 336, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 358, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/config/custom_components/bhyve/switch.py", line 148, in async_turn_on
    await self._send_station_message(station_payload)
  File "/config/custom_components/bhyve/switch.py", line 139, in _send_station_message
    await self._bhyve.send_message(payload)
TypeError: object NoneType can't be used in 'await' expression

**Comment by sebr** [comment]
@retroneo can you please check you have the latest version installed? That code doesn't look like it's coming from my integration

@monsieurlatte I have fixed this issue in `0.1.2`. Thanks for reporting!

**Comment by retroneo** [comment]
got it working with 0.1.2. Thanks!

Any chance you can extract the flow rate while the sprinkler is running?

**Comment by sebr** [comment]
@retroneo thanks, I’ll close this issue out!

Would be happy to add support for the flow data however will need you to do some debugging for me (my flow sensor doesn’t work as it doesn’t use enough water)

I’ll create a new issue for it.
