### ISSUE TITLE
"Cannot write to closing transport" after 2021.3.0

### ISSUE THREAD

**Issue by jjprz** [sebr/bhyve-home-assistant#53]
**Describe the bug**
Bhyve Component shows an error after update to 2021.3.0
Entities display correctly but switches don't work

**BHyve devices**
BHyve Hose Faucet Timer

```log
Traceback (most recent call last):
  File "/config/custom_components/bhyve/pybhyve/websocket.py", line 57, in _ping
    await self._ws.send_str(json.dumps({"event": "ping"}))
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_ws.py", line 150, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 687, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 598, in _send_frame
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```

**Comment by saqibbutt-dnd** [comment]
hi @jjprz I am still seeing this how did u resolve this? Thanks
