### ISSUE TITLE
switch creation error after update to 0.1.9  

### ISSUE THREAD

**Issue by nnhhuu** [sebr/bhyve-home-assistant#6]
Good morning, 

over the weekend I updated the component to the latest version (0.1.9), in the new version there is an error creating a switch.

2020-02-24 07:36:59 DEBUG (MainThread) [custom_components.bhyve.switch] Watering program {'name': 'Todo', 'program_start_date': None, 'frequency': {'type': 'days', 'days': [1, 3, 5]}, 'program_end_date': None, 'updated_at': '2020-01-16T15:33:09.426Z', 'updated_via': None, 'start_times': ['03:30'], 'id': '5c1956264f0c88ec9ed50383', 'budget': 100, 'is_smart_program': False, 'device_id': '5a90c9804f0c72b5d61f5d3b', 'program': 'b', 'run_times': [{'run_time': 30, 'station': 1}, {'run_time': 30, 'station': 2}, {'run_time': 30, 'station': 3}, {'run_time': 30, 'station': 4}, {'run_time': 30, 'station': 5}, {'run_time': 30, 'station': 6}, {'run_time': 30, 'station': 7}, {'run_time': 30, 'station': 8}], 'enabled': True, 'created_at': '2018-12-18T20:18:46.088Z'}
**2020-02-24 07:36:59 ERROR (MainThread) [homeassistant.components.switch] Error while setting up bhyve platform for switch**
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 159, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/bhyve/switch.py", line 44, in async_setup_platform
    hass, bhyve, device, zone, name, programs, "water-pump"
  File "/config/custom_components/bhyve/switch.py", line 64, in __init__
    super().__init__(hass, bhyve, device, name, icon, DEVICE_CLASS_SWITCH)
  File "/config/custom_components/bhyve/__init__.py", line 157, in __init__
    self._setup(device)
  File "/config/custom_components/bhyve/switch.py", line 111, in _setup
    self._set_watering_program(program)
  File "/config/custom_components/bhyve/switch.py", line 127, in _set_watering_program
    program_name = program.get("name", "Unknown")
NameError: name 'program' is not defined

seems to be something with the "programs" in the bhyve. 

Any suggestion? 

Thank you

**Comment by sebr** [comment]
@nnhhuu are you sure that the integration was updated to v 0.1.9 correctly?

The message included in your thread was removed in 7b281d0 and there was a subsequent fix for a startup issue which looks very similar in 0367e4a.

It looks like you may have updated to v 0.1.8 which had this issue.

**Comment by nnhhuu** [comment]
problem solved, i uninstall and install it again,  Thank you ...
