### ISSUE TITLE
error adding devices in 0.1.9

### ISSUE THREAD

**Issue by NotSteveAtGithub** [sebr/bhyve-home-assistant#7]
I've had two hub/timer combinations working since the very first release.  Recently I bought two more and added them in the app.  

After the next restart, I'm getting these errors:

2020-03-11 21:15:26 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up bhyve platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/bhyve/binary_sensor.py", line 35, in async_setup_platform
    hass, bhyve, device, name, sensor_type["icon"]
  File "/config/custom_components/bhyve/__init__.py", line 157, in __init__
    self._setup(device)
  File "/config/custom_components/bhyve/binary_sensor.py", line 51, in _setup
    rain_delay = device_status["rain_delay"]
KeyError: 'rain_delay'

Also, "rain_delay" for the existing devices now shows "unknown".  This may have been the case before I added the new devices,  so I can't quite say which version might have introduced this.

**Comment by sebr** [comment]
@NotSteveAtGithub I've tracked down the error and published v0.1.10. Can you please update and take a look?

It's interesting that your device is not returning any `rain_delay` attribute. If you wouldn't mind [enabling logging](https://github.com/sebr/bhyve-home-assistant#debugging) (packet dump not required) and sending the `devices` object from your console that would help me ensure that your devices are being parsed properly.

Thanks!

**Comment by NotSteveAtGithub** [comment]
@sebr Thanks for the quick fix!  After upgrade to v0.1.10, battery_level and rain_delay are present on the new device, and rain_delay is back to normal for the older devices.  I don't yet see the switch or the zone state for the new device.  Will try to get a log to you this evening.  Thanks again!

**Comment by NotSteveAtGithub** [comment]
Here's the devices object:

2020-03-12 17:43:55 DEBUG (MainThread) [custom_components.bhyve] Devices: [{'last_connected_at': '2020-02-25T03:29:39.653Z', 'address': 'REDACTED', 'timezone': {'dst_offset': 3600, 'raw_offset': -21600, 'timezone_id': 'America/Chicago', 'timezone_name': 'Central Daylight Time'}, 'full_location': 'REDACTED', 'firmware_version': '0030', 'name': 'North Hub', 'type': 'bridge', 'updated_at': '2020-02-25T03:29:39.654Z', 'reference': '446755210739', 'mac_address': '446755210739', 'mesh_id': '5d5cae814f0c47ece9ea4a75', 'status': {'watering_status': None, 'next_start_time': '1970-01-01T00:00:00-06:00', 'next_start_programs': []}, 'wifi_version': 0, 'id': '5d5cae814f0c47ece9ea4a73', 'num_stations': 0, 'user_id': '5d5cadcf4f0c47ece9ea4a58', 'device_gateway_topic': 'devices-1', 'hardware_version': 'BH1-0001', 'is_connected': True, 'location': 'REDACTED', 'created_at': '2019-08-21T02:37:53.694Z'}, {'last_connected_at': '2020-02-25T03:29:39.655Z', 'address': 'REDACTED', 'water_sense_mode': 'off', 'scheduled_modes': {'auto': {'at': '', 'annually': False}, 'off': {'at': '', 'annually': False}}, 'timezone': {'dst_offset': 3600, 'raw_offset': -21600, 'timezone_id': 'America/Chicago', 'timezone_name': 'Central Daylight Time'}, 'full_location': 'REDACTED', 'weather_forecast_location_id': '5caf84ba4f0c77eadcf01010', 'firmware_version': '0041', 'name': 'North Hose Timer', 'type': 'sprinkler_timer', 'manual_preset_runtime_sec': 2700, 'battery': {'percent': 98, 'charging': False}, 'restricted_frequency': None, 'weather_delay_thresholds': {'precip_prob': 30, 'precip_in': 0.125, 'wind_speed_mph': 20, 'freeze_temp_f': 37}, 'updated_at': '2020-03-12T12:06:38.084Z', 'reference': '446755210739-32877', 'mac_address': '4467551285de', 'weather_station_id': '5a30260e4f0cd78da02ba755', 'mesh_id': '5d5cae814f0c47ece9ea4a75', 'status': {'run_mode': 'auto', 'next_start_programs': ['a'], 'watering_status': None, 'rain_delay_suggested_at': '2020-03-12T10:41:23.910Z', 'rain_delay': 0, 'flow_sensor': None, 'next_start_time': '2020-01-19T03:00:00-06:00', 'rain_delay_started_at': '2020-03-08T12:02:48.000Z'}, 'id': '5d5caef44f0c47ece9ea4a91', 'num_stations': 1, 'notes': '', 'zones': [{'station': 1, 'slope_grade': 0, 'sun_shade': 'full_shade', 'name': 'North Zone', 'num_sprinklers': 0, 'catch_cup_volumes': [], 'catch_cup_run_time': 0, 'smart_watering_enabled': False}], 'user_id': '5d5cadcf4f0c47ece9ea4a58', 'google_home_status': None, 'device_gateway_topic': 'devices-1', 'hardware_version': 'HT25-0000', 'is_connected': True, 'location': 'REDACTED', 'created_at': '2019-08-21T02:39:48.624Z', 'suggested_start_time': None, 'et_id': '5644ff07ad27a7777ff6ca07'}, {'last_connected_at': '2020-03-11T22:44:07.050Z', 'address': 'REDACTED', 'timezone': {'dst_offset': 3600, 'raw_offset': -21600, 'timezone_id': 'America/Chicago', 'timezone_name': 'Central Daylight Time'}, 'full_location': 'REDACTED', 'firmware_version': '0030', 'name': 'South Hub', 'type': 'bridge', 'updated_at': '2020-03-11T22:44:08.618Z', 'reference': '44675520ab4f', 'mac_address': '44675520ab4f', 'mesh_id': '5d5cb2ca4f0c47ece9ea4b66', 'status': {'watering_status': None, 'next_start_time': '1970-01-01T00:00:00-05:00', 'next_start_programs': []}, 'wifi_version': 0, 'id': '5d5cb2ca4f0c47ece9ea4b64', 'num_stations': 0, 'user_id': '5d5cadcf4f0c47ece9ea4a58', 'device_gateway_topic': 'devices-1', 'hardware_version': 'BH1-0001', 'is_connected': True, 'location': 'REDACTED', 'created_at': '2019-08-21T02:56:10.366Z'}, {'last_connected_at': '2020-03-11T22:44:07.052Z', 'address': 'REDACTED', 'water_sense_mode': 'off', 'scheduled_modes': {'auto': {'at': '', 'annually': False}, 'off': {'at': '', 'annually': False}}, 'timezone': {'dst_offset': 3600, 'raw_offset': -21600, 'timezone_id': 'America/Chicago', 'timezone_name': 'Central Daylight Time'}, 'full_location': 'REDACTED', 'weather_forecast_location_id': '5caf84ba4f0c77eadcf01010', 'firmware_version': '0041', 'name': 'South Hose Timer', 'type': 'sprinkler_timer', 'manual_preset_runtime_sec': 2700, 'battery': {'percent': 94, 'charging': False}, 'restricted_frequency': None, 'weather_delay_thresholds': {'precip_prob': 30, 'precip_in': 0.125, 'wind_speed_mph': 20, 'freeze_temp_f': 37}, 'updated_at': '2020-03-12T10:41:27.754Z', 'reference': '44675520ab4f-43899', 'mac_address': '44675511befc', 'weather_station_id': '5a30260e4f0cd78da02ba755', 'mesh_id': '5d5cb2ca4f0c47ece9ea4b66', 'status': {'run_mode': 'auto', 'next_start_programs': ['a'], 'watering_status': None, 'rain_delay_suggested_at': '2020-03-12T10:41:27.754Z', 'rain_delay': 0, 'flow_sensor': None, 'next_start_time': '2020-01-19T03:15:00-06:00', 'rain_delay_started_at': '2020-03-08T12:03:53.000Z'}, 'id': '5d5cb33f4f0c47ece9ea4b74', 'num_stations': 1, 'notes': '', 'zones': [{'station': 1, 'slope_grade': 0, 'sun_shade': 'full_shade', 'name': 'South Zone', 'num_sprinklers': 0, 'catch_cup_volumes': [], 'catch_cup_run_time': 0, 'smart_watering_enabled': False}], 'user_id': '5d5cadcf4f0c47ece9ea4a58', 'google_home_status': None, 'device_gateway_topic': 'devices-1', 'hardware_version': 'HT25-0000', 'is_connected': True, 'location': 'REDACTED', 'created_at': '2019-08-21T02:58:07.640Z', 'suggested_start_time': None, 'et_id': '5644ff07ad27a7777ff6ca07'}, {'last_connected_at': '2020-03-12T03:21:27.444Z', 'address': 'REDACTED', 'timezone': {'dst_offset': 3600, 'raw_offset': -21600, 'timezone_id': 'America/Chicago', 'timezone_name': 'Central Daylight Time'}, 'full_location': 'REDACTED', 'firmware_version': '0030', 'name': 'Northeast Hub', 'type': 'bridge', 'updated_at': '2020-03-12T03:21:27.518Z', 'reference': '4467552039ff', 'mac_address': '4467552039ff', 'mesh_id': '5e696baf4f0c7eccad2e403f', 'status': {'watering_status': None, 'next_start_time': '1970-01-01T00:00:00-05:00', 'next_start_programs': []}, 'wifi_version': 0, 'id': '5e696baf4f0c7eccad2e403d', 'num_stations': 0, 'user_id': '5d5cadcf4f0c47ece9ea4a58', 'device_gateway_topic': 'devices-2', 'hardware_version': 'BH1-0001', 'is_connected': True, 'location': 'REDACTED', 'created_at': '2020-03-11T22:52:31.060Z'}, {'last_connected_at': '2020-03-12T03:21:27.446Z', 'address': 'REDACTED', 'water_sense_mode': 'off', 'scheduled_modes': {'auto': {'at': '', 'annually': False}, 'off': {'at': '', 'annually': False}}, 'timezone': {'dst_offset': 3600, 'raw_offset': -21600, 'timezone_id': 'America/Chicago', 'timezone_name': 'Central Daylight Time'}, 'full_location': 'REDACTED', 'weather_forecast_location_id': '5afa18844f0c27e63befd2eb', 'firmware_version': '41', 'name': 'Northeast Timer', 'type': 'sprinkler_timer', 'manual_preset_runtime_sec': 2700, 'battery': {'percent': 100, 'charging': False}, 'restricted_frequency': None, 'weather_delay_thresholds': {'precip_prob': 30, 'precip_in': 0.125, 'wind_speed_mph': 20, 'freeze_temp_f': 37}, 'updated_at': '2020-03-12T12:12:10.261Z', 'reference': '4467552039ff-12689', 'mac_address': '446755110829', 'weather_station_id': '5a302b374f0caaed3d54e044', 'mesh_id': '5e696baf4f0c7eccad2e403f', 'status': {'run_mode': 'auto', 'next_start_programs': [], 'watering_status': None, 'rain_delay_suggested_at': '2020-03-12T12:12:10.261Z', 'flow_sensor': None, 'next_start_time': '2106-02-07T01:28:15-05:00'}, 'id': '5e696fe14f0cb5aa04819154', 'num_stations': 1, 'notes': '', 'zones': [{'station': 1, 'slope_grade': 0, 'sun_shade': 'partial_shade', 'name': '', 'num_sprinklers': 0, 'catch_cup_volumes': [], 'catch_cup_run_time': 0, 'smart_watering_enabled': False}], 'user_id': '5d5cadcf4f0c47ece9ea4a58', 'google_home_status': None, 'device_gateway_topic': 'devices-2', 'hardware_version': 'HT25-0000', 'is_connected': True, 'location': 'REDACTED', 'created_at': '2020-03-11T23:10:25.143Z', 'suggested_start_time': None, 'et_id': '5644ff08ad27a7777ff6caea'}, {'last_connected_at': '2020-03-12T03:21:53.568Z', 'address': 'REDACTED', 'timezone': {'dst_offset': 3600, 'raw_offset': -21600, 'timezone_id': 'America/Chicago', 'timezone_name': 'Central Daylight Time'}, 'full_location': 'REDACTED', 'firmware_version': '0030', 'name': 'Southeast Hub', 'type': 'bridge', 'updated_at': '2020-03-12T03:21:53.651Z', 'reference': '446755208daf', 'mac_address': '446755208daf', 'mesh_id': '5e6971814f0cb5aa04819172', 'status': {'watering_status': None, 'next_start_time': '1970-01-01T00:00:00-05:00', 'next_start_programs': []}, 'wifi_version': 0, 'id': '5e6971814f0c7eccad2e409d', 'num_stations': 0, 'user_id': '5d5cadcf4f0c47ece9ea4a58', 'device_gateway_topic': 'devices-2', 'hardware_version': 'BH1-0001', 'is_connected': True, 'location': 'REDACTED', 'created_at': '2020-03-11T23:17:21.388Z'}]
2020-03-12 17:43:55 DEBUG (MainThread) [custom_components.bhyve] Programs: [{'pending_timer_ack': True, 'name': 'North 45 mins', 'program_start_date': None, 'frequency': {'type': 'interval', 'interval': 7, 'interval_start_time': '2019-10-20T05:00:00.000Z'}, 'program_end_date': None, 'updated_at': '2020-01-17T14:13:37.744Z', 'updated_via': 'wifi', 'start_times': ['03:00', '03:30', '04:00'], 'id': '5d5cb2144f0c47ece9ea4b4b', 'budget': 100, 'device_id': '5d5caef44f0c47ece9ea4a91', 'program': 'a', 'run_times': [{'run_time': 15, 'station': 1}], 'enabled': False, 'created_at': '2019-08-21T02:53:08.503Z'}, {'name': 'Unused', 'frequency': {'type': 'odd'}, 'updated_at': '2019-08-21T10:32:24.640Z', 'start_times': ['03:15', '03:45', '04:15'], 'id': '5d5cb4924f0c47ece9ea4ba4', 'budget': 100, 'device_id': '5d5caef44f0c47ece9ea4a91', 'program': 'b', 'run_times': [{'run_time': 15, 'station': 1}], 'enabled': False, 'created_at': '2019-08-21T03:03:46.915Z'}, {'pending_timer_ack': True, 'name': 'South 45 Mins', 'program_start_date': None, 'frequency': {'type': 'interval', 'interval': 7, 'interval_start_time': '2019-10-20T05:00:00.000Z'}, 'program_end_date': None, 'updated_at': '2020-01-17T14:13:47.054Z', 'updated_via': 'wifi', 'start_times': ['03:15', '03:45', '04:15'], 'id': '5d5cb7b24f0c47ece9ea4c07', 'budget': 100, 'device_id': '5d5cb33f4f0c47ece9ea4b74', 'program': 'a', 'run_times': [{'run_time': 15, 'station': 1}], 'enabled': False, 'created_at': '2019-08-21T03:17:06.644Z'}]

**Comment by NotSteveAtGithub** [comment]
@sebr , after digging through the data above and comparing the ones with and without rain_delay, it seems that this only happens if the new device doesn't have any programs defined in the app.  My hope in all of this was to do as absolutely little in the app as necessary so I could control it all from HA.  So for now I've figured out a workaround - define a program even if you're not going to use it - and then everything is created.

**Comment by sebr** [comment]
Thanks for looking into this @NotSteveAtGithub ! I don't blame you for wanting to do as little as possible in that app 🙈
